
spring.docker.compose:
  enabled: true
  file: ../../docker/regtest/docker-compose.yml
  stop.command: DOWN # STOP is default, DOWN stops and removes containers and networks
  skip.in-tests: false

org.tbk.lightning.lnd.grpc:
  enabled: true
  host: localhost
  port: 20009
  # from hex (`xxd -ps -u -c 1000 ./docker/regtest/data/lnd/data/chain/bitcoin/regtest/admin.macaroon`) to base64
  macaroon-base64: 'AgEDbG5kAvgBAwoQ0YDYH8PVidWRKzzwY/7h/RIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaIQoIbWFjYXJvb24SCGdlbmVyYXRlEgRyZWFkEgV3cml0ZRoWCgdtZXNzYWdlEgRyZWFkEgV3cml0ZRoXCghvZmZjaGFpbhIEcmVhZBIFd3JpdGUaFgoHb25jaGFpbhIEcmVhZBIFd3JpdGUaFAoFcGVlcnMSBHJlYWQSBXdyaXRlGhgKBnNpZ25lchIIZ2VuZXJhdGUSBHJlYWQAAAYgL9Ny8QJfFoQy3MaOKHIuXblpVrWNkI7HPmRZYiEarDY='
  # tls cert file (`./docker/regtest/data/lnd/tls.cert`) as base64
  cert-base64: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKVENDQWNxZ0F3SUJBZ0lRRTdSbVN0TE1rSUZxQkkrNTJTMytVREFLQmdncWhrak9QUVFEQWpBNE1SOHcKSFFZRFZRUUtFeFpzYm1RZ1lYVjBiMmRsYm1WeVlYUmxaQ0JqWlhKME1SVXdFd1lEVlFRREV3eGtaR0ZpWmpWbQpaREprWVRZd0hoY05Nak13TnpFM01UQXhOak01V2hjTk1qUXdPVEV3TVRBeE5qTTVXakE0TVI4d0hRWURWUVFLCkV4WnNibVFnWVhWMGIyZGxibVZ5WVhSbFpDQmpaWEowTVJVd0V3WURWUVFERXd4a1pHRmlaalZtWkRKa1lUWXcKV1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVEwZlk2WnhPY1g2ejFmN2loZ0dCdUJCMzA1SUtCaQpJTFBQWm1HSENqbVcxTnBYQVQwK09yS0oxaHlLVTlGMm9KbXRXS2Q3OFFwdnJDL1k5bDVqN0tMNm80RzFNSUd5Ck1BNEdBMVVkRHdFQi93UUVBd0lDcERBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlJRZ1lodWs3WU0wV1U1eDEvVGlDWTBwR0RmTmpCYkJnTlZIUkVFVkRCUwpnZ3hrWkdGaVpqVm1aREprWVRhQ0NXeHZZMkZzYUc5emRJSUVkVzVwZUlJS2RXNXBlSEJoWTJ0bGRJSUhZblZtClkyOXVib2NFZndBQUFZY1FBQUFBQUFBQUFBQUFBQUFBQUFBQUFZY0VyQk1BQXpBS0JnZ3Foa2pPUFFRREFnTkoKQURCR0FpRUFyNFBXbjBpY3VKVnJUSE9vQXRVZTNlYXpuZ0pnUG9uSTZURnJhQ1haanNzQ0lRRHcwOVh1dUwwQgpjU2h3SUNBdkJtWDZUZnJKMklSZ01YUmUxTXBuUUlNM1VnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: regtest-rpc-user
  rpcpassword: regtest-rpc-pass

org.tbk.bitcoin.regtest:
  enabled: true
  mining:
    enabled: true
    # an address from "default_wallet" with key:
    # truth fever mom transfer steak immense lake jacket glide bring fancy electric
    coinbase-reward-address: bcrt1q0xtrupsjmqr7u7xz4meufd3a8pt6v553m8nmvz
    mine-initial-amount-of-blocks: 1
