app.name: lad-dev
app.description: A spring boot bitcoin demo application
app.home: '${user.home}/.lad-dev'

spring.application.name: '${app.name}'
spring.http.log-request-details: true

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.name: '${app.home}/${app.name}.log'
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
logging.level.web: DEBUG

spring.jpa.show-sql: false # true


org.tbk.bitcoin.regtest:
  enabled: true
  # mine blocks every 1 - 10 seconds
  mining:
    enabled: true
    # an address from "default_wallet" with key:
    # truth fever mom transfer steak immense lake jacket glide bring fancy electric
    coinbase-reward-address: bcrt1q0xtrupsjmqr7u7xz4meufd3a8pt6v553m8nmvz
    mine-initial-amount-of-blocks: 99
    next-block-duration:
      min-duration: PT1S
      max-duration: PT10S


org.tbk.spring.testcontainer.lnd:
  enabled: true
  restport: 20080
  rpcport: 20009
  commands:
    - '--alias=tbk-lnd-example-application'
    - '--bitcoind.rpcuser=myoneandonlyrpcuser'
    - '--bitcoind.rpcpass=correcthorsebatterystaple123'

org.tbk.spring.testcontainer.bitcoind:
  enabled: true
  rpcuser: myoneandonlyrpcuser
  rpcpassword: correcthorsebatterystaple123
  exposed-ports:
    - 28332
    - 28333
  commands:
    # [zeromq]
    # Enable publishing of raw block hex to <address>.
    - '-zmqpubrawblock=tcp://0.0.0.0:28332'
    # Enable publishing of raw transaction hex to <address>.
    - '-zmqpubrawtx=tcp://0.0.0.0:28333'
    # [rpc]
    # Number of seconds after which an uncompleted RPC call will time out
    - '-rpcservertimeout=10' # default is 30
    # [debug]
    # Enable debug logging for categories.
    # '-debug=1' would log ALL messages
    - '-debug=rpc,zmq'
    # Log IP Addresses in debug output.
    - '-logips=1'
    # Append comment to the user agent string.
    - '-uacomment=tbk-bitcoin-spring-boot-starter-lnd-playground-example-app'
    # Allows you to test address relay on localhost.
    - '-addrmantest=1'
    # Send trace/debug info to console instead of debug.log.
    - '-printtoconsole=1'

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: myoneandonlyrpcuser
  rpcpassword: correcthorsebatterystaple123